---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: prometheus
  namespace: default
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      scrape_configs:
        - job_name: 'node-exporter'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_endpoints_name]
              regex: 'node-exporter'
              action: keep
    # scrape_configs:
    #   - job_name: 'node-exporter'
    #     kubernetes_sd_configs:
    #       - role: endpoints
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_endpoints_name]
    #         regex: 'node-exporter'
    #         action: keep
    # scrape_configs:
    #   - job_name: 'node-exporter'
    #     static_configs:
    #       - targets: ['node-exporter-service:9100']
    #     honor_labels: true
    #     scrape_interval: 15s
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prometheus
  labels:
    app: prometheus
  namespace: default
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /ets/prometheus
          resources:
            requests:
              memory: 122Mi
            limits:
              memory: 122Mi
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
            defaultMode: 420
---
apiVersion: v1 
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 30090
      targetPort: 9090
  type: LoadBalancer


